export class ScholarshipForm {
    constructor(
        public aadharNumber:String,
        public religion:String,
        public category:String,
        public fatherName:String,
        public motherName:String,
        public familyAnnualIncome:String,
        public rollNo10:String,
        public board10:String,
        public passingYear10:String,
        public marksObtained10:String,
        public rollNo12:String,
        public board12:String,
        public passingYear12:String,
        public marksObtained12:String,
        public admissionFee:string,
        public tuitionFee:String,
        public otherFee:String,
        public isDisabled:String,
        public typeOfDisability:String,
        public percentOfDisability:String,
        public maritalStatus:String,
        public fatherProfession:String,
        public motherProfession:String,
        public state:String,
        public district:String,
        public block:String,
        public houseNo:String,
        public streetNo:String,
        public pincode:String,
        public chooseScheme:String,
        public domicileCertificate:String,
        public studentPhotograph:String,
        public instituteIdCard:String,
        public casteIncomeCertificate:String,
        public previousYearMarksheet:String,
        public feeReceiptOfCurrentYear:String,
        public bankPassbookFrontPage:String,
        public aadharCard:String,
        public marksheet10:String,
        public marksheet12:String,
        public formStatus:boolean,
    ){}
}
